#!/bin/bash

# invoke global X session script
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

usr/bin/pipewire &
usr/bin/pipewire-pulse &
usr/bin/pipewire-media-session &

xwallpaper --zoom $HOME/personal/photos\ \&\ videos/Wallpapers/nord-theme/GMV5L7.jpg &

#dunst
dunst &

#picom
picom &

#Sxhkd
sxhkd &

#Dwmblocks
dwmblocks &

#dwm
exec dwm 
