#!/bin/bash

# invoke global X session script
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xwallpaper --zoom $HOME/personal/pix/wallpapers/nord-theme/underwater.png &

#picom
picom --experimental-backends &

#Sxhkd
sxhkd &

#Dwmblocks
dwmblocks &

#dwm
exec dwm 
